spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: false #cicd에서 실행 담당하도록 자동 실행 방지, flywayMigrate으로 반영
    baseline-on-migrate: true #기존 테이블 있는 경우를 포함해 적용
    baseline-version: "0" #테이블 없으면 0부터 시작
    locations:
      - classpath:db/migration

  # DB 설정: Spring 표준 키 사용 (Doppler에 있는 키와 매칭)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 스키마 변경 방지 (운영 표준)
    show-sql: false

logging:
  level:
    root: WARN
    com.beyond.qiin: INFO