server:
  port: ${SERVER_PORT:8080} # 환경 변수가 없으면 기본값 8080 사용

spring:
  profiles:
    default: dev

  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}                                      # Kafka 접속 정보 지정
    producer:
      #직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer   
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  
    topic:
      reservation-topic: reservation-topic
      notification-topic: notification-topic
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      #역직렬화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer     
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer   


# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    org.springframework: INFO
    com.adjh.springbootkafka: DEBUG
    org:
      apache.kafka: INFO
      springframework.kafka: INFO