name: CD Deploy Production (Fargate)


on:
  workflow_run:
    workflows: ["CI Build"]   # ğŸ‘ˆ CI ì´ë¦„ê³¼ ì •í™•íˆ ì¼ì¹˜
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      # Step 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2. AWS ì¸ì¦
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3. ECR ë¡œê·¸ì¸
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4. í™˜ê²½ ë³€ìˆ˜ ì„¤ì •
      - name: Set ENV
        run: |
          echo "ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/qiin-backend" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      # Step 5. Docker ì´ë¯¸ì§€ ë¹Œë“œ
      - name: Build Docker Image
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG ./qiin-be

      # Step 6. Docker ì´ë¯¸ì§€ Push
      - name: Push Docker Image
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      # Step 7. ECS ì„œë¹„ìŠ¤ ê°•ì œ ì—…ë°ì´íŠ¸
      - name: Deploy New Task Definition to ECS
        run: |
          aws ecs update-service \
            --cluster qiin-fargate-cluster \
            --service qiin-service \
            --force-new-deployment
