name: CD Staging Deploy

on:
  push:
    branches:
      - staging
      - feature/52-staging   # 테스트용으로 임시 유지

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Staging Containers
        run: |
          cd C:\Users\Playdata\develop\be18-fin-jelly-queuein-be\qiin-be

          echo "Stopping running containers..."
          docker compose -f docker-compose.staging.yml down

          echo "Starting staging containers with Doppler..."
          doppler --token "${{ secrets.DOPPLER_STAGING_TOKEN }}" run --config stg -- docker compose -f docker-compose.staging.yml up -d
        shell: pwsh
